"""initial migration

Revision ID: 3855d7ad8b03
Revises: 
Create Date: 2026-05-10 02:14:46.351499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3855d7ad8b03'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_locations_city_state'), table_name='saved_locations')
    op.drop_index(op.f('ix_saved_locations_primary'), table_name='saved_locations')
    op.drop_index(op.f('ix_saved_locations_user_id'), table_name='saved_locations')
    op.drop_table('saved_locations')
    op.drop_index(op.f('ix_alert_preferences_user_id'), table_name='alert_preferences')
    op.drop_table('alert_preferences')
    op.drop_index(op.f('ix_device_tokens_active'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_platform'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index(op.f('ix_forecast_logs_generated_at'), table_name='forecast_logs')
    op.drop_index(op.f('ix_forecast_logs_location_id'), table_name='forecast_logs')
    op.drop_index(op.f('ix_forecast_logs_user_id'), table_name='forecast_logs')
    op.drop_table('forecast_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_onboarding_completed'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_notification_logs_sent_at'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_status'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_type'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_user_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_logs',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_token_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('notification_type', sa.VARCHAR(length=22), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payload_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('provider_response_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_token_id'], ['device_tokens.id'], name=op.f('fk_notification_logs_device_token_id_device_tokens'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_logs'))
    )
    op.create_index(op.f('ix_notification_logs_user_id'), 'notification_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_notification_logs_type'), 'notification_logs', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notification_logs_status'), 'notification_logs', ['status'], unique=False)
    op.create_index(op.f('ix_notification_logs_sent_at'), 'notification_logs', ['sent_at'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('health_profile', sa.VARCHAR(length=23), autoincrement=False, nullable=False),
    sa.Column('sensitivity_level', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('preferred_activity_types', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('display_preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_profiles_user_id'))
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('firebase_uid', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('onboarding_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('firebase_uid', name=op.f('uq_users_firebase_uid'))
    )
    op.create_index(op.f('ix_users_onboarding_completed'), 'users', ['onboarding_completed'], unique=False)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('forecast_logs',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('source_type', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('forecast_horizon_hours', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('predicted_aqi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('predicted_category', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('recommendation_summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['saved_locations.id'], name=op.f('fk_forecast_logs_location_id_saved_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_forecast_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_logs'))
    )
    op.create_index(op.f('ix_forecast_logs_user_id'), 'forecast_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_forecast_logs_location_id'), 'forecast_logs', ['location_id'], unique=False)
    op.create_index(op.f('ix_forecast_logs_generated_at'), 'forecast_logs', ['generated_at'], unique=False)
    op.create_table('device_tokens',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('fcm_token', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('device_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_device_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_tokens')),
    sa.UniqueConstraint('fcm_token', name=op.f('uq_device_tokens_fcm_token'))
    )
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_device_tokens_platform'), 'device_tokens', ['platform'], unique=False)
    op.create_index(op.f('ix_device_tokens_active'), 'device_tokens', ['is_active'], unique=False)
    op.create_table('alert_preferences',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('alert_4h', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('alert_6h', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('alert_12h', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('alert_24h', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('daily_summary_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('best_time_alert_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('threshold_aqi', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notify_for_mask_recommendation', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('notify_for_avoid_outdoor', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('quiet_hours_start', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('quiet_hours_end', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alert_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_preferences')),
    sa.UniqueConstraint('user_id', name=op.f('uq_alert_preferences_user_id'))
    )
    op.create_index(op.f('ix_alert_preferences_user_id'), 'alert_preferences', ['user_id'], unique=False)
    op.create_table('saved_locations',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=96), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=96), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=96), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_locations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_locations'))
    )
    op.create_index(op.f('ix_saved_locations_user_id'), 'saved_locations', ['user_id'], unique=False)
    op.create_index(op.f('ix_saved_locations_primary'), 'saved_locations', ['user_id', 'is_primary'], unique=False)
    op.create_index(op.f('ix_saved_locations_city_state'), 'saved_locations', ['city', 'state'], unique=False)
    # ### end Alembic commands ###
